version: "3"

services:
  app-employee-manager:
    build: employeemanager
    mem_limit: 512m
    ports: 
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://employee_db:3306/employee_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD:
    restart: always
    depends_on: 
      employee_db:
        condition: service_healthy

  employee_db:
    image: mysql:8.2.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: employee_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

